name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/run-cmake@v3

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest --output-on-failure